/** Modelos PostgreSQL persistentes da Videlis. */
import { boolean, index, integer, pgEnum, pgTable, serial, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";

const touch = () => new Date();
export const userRole = pgEnum("user_role", ["user", "admin"]);
export const cycleKind = pgEnum("cycle_kind", ["monthly", "quarterly", "semiannual", "annual", "custom"]);
export const customerStatus = pgEnum("customer_status", ["active", "attention", "expired"]);
export const epgStatus = pgEnum("epg_status", ["healthy", "attention", "inactive"]);
export const vodKind = pgEnum("vod_kind", ["filme", "serie", "novela"]);
export const vodStatus = pgEnum("vod_status", ["draft", "ready"]);
export const pixStatus = pgEnum("pix_status", ["pending", "approved", "expired", "cancelled"]);
export const androidReleaseStatus = pgEnum("android_release_status", ["draft", "published", "archived"]);

export const users = pgTable("users", { id: serial("id").primaryKey(), openId: varchar("open_id", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("login_method", { length: 64 }), passwordHash: varchar("password_hash", { length: 256 }), role: userRole("role").default("user").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull(), lastSignedIn: timestamp("last_signed_in", { withTimezone: true }).defaultNow().notNull() });

export const plans = pgTable("plans", { id: serial("id").primaryKey(), name: varchar("name", { length: 100 }).notNull(), monthlyPriceCents: integer("monthly_price_cents").notNull(), screenLimit: integer("screen_limit").default(1).notNull(), trialDays: integer("trial_days").default(0).notNull(), isActive: boolean("is_active").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const planCycles = pgTable("plan_cycles", { id: serial("id").primaryKey(), planId: integer("plan_id").notNull(), cycle: cycleKind("cycle").notNull(), intervalDays: integer("interval_days").notNull(), discountPercent: integer("discount_percent").default(0).notNull(), isActive: boolean("is_active").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });

export const customers = pgTable("customers", { id: serial("id").primaryKey(), label: varchar("label", { length: 90 }).notNull(), email: varchar("email", { length: 320 }), phone: varchar("phone", { length: 30 }), plan: varchar("plan", { length: 64 }).notNull(), planId: integer("plan_id"), planCycleId: integer("plan_cycle_id"), screenLimit: integer("screen_limit").default(1).notNull(), usedScreens: integer("used_screens").default(0).notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), trialEndsAt: timestamp("trial_ends_at", { withTimezone: true }), accessTokenHash: varchar("access_token_hash", { length: 64 }).notNull().unique(), xtreamUsername: varchar("xtream_username", { length: 16 }).notNull().unique(), xtreamPasswordHash: varchar("xtream_password_hash", { length: 64 }).notNull().unique(), status: customerStatus("status").default("active").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const customerDevices = pgTable("customer_devices", { id: serial("id").primaryKey(), customerId: integer("customer_id").notNull(), slot: integer("slot").notNull(), deviceName: varchar("device_name", { length: 120 }).notNull(), deviceKeyHash: varchar("device_key_hash", { length: 64 }).notNull().unique(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, table => [uniqueIndex("customer_devices_customer_slot_unique").on(table.customerId, table.slot)]);
export const playbackSessions = pgTable("playback_sessions", { id: serial("id").primaryKey(), customerId: integer("customer_id").notNull(), consumerKeyHash: varchar("consumer_key_hash", { length: 64 }).notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, table => [uniqueIndex("playback_sessions_customer_consumer_unique").on(table.customerId, table.consumerKeyHash), index("playback_sessions_active_lookup").on(table.customerId, table.expiresAt)]);

export const channels = pgTable("channels", { id: serial("id").primaryKey(), channelNumber: integer("channel_number").notNull(), name: varchar("name", { length: 140 }).notNull(), groupTitle: varchar("group_title", { length: 90 }).notNull(), epgId: varchar("epg_id", { length: 160 }), logoUrl: text("logo_url"), qualities: varchar("qualities", { length: 120 }).notNull(), ageRating: integer("age_rating").default(0).notNull(), routeCount: integer("route_count").default(1).notNull(), healthStatus: varchar("health_status", { length: 16 }).default("unknown").notNull(), lastHealthAt: timestamp("last_health_at", { withTimezone: true }), healthMessage: text("health_message"), isActive: boolean("is_active").default(false).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const channelSources = pgTable("channel_sources", { id: serial("id").primaryKey(), channelId: integer("channel_id").notNull(), quality: varchar("quality", { length: 24 }).notNull(), primaryUrl: text("primary_url").notNull(), primaryOrigin: varchar("primary_origin", { length: 500 }), primaryReferer: varchar("primary_referer", { length: 500 }), primaryLastStatus: integer("primary_last_status"), primaryLatencyMs: integer("primary_latency_ms"), primaryLastError: text("primary_last_error"), fallbackUrl: text("fallback_url"), fallbackOrigin: varchar("fallback_origin", { length: 500 }), fallbackReferer: varchar("fallback_referer", { length: 500 }), fallbackLastStatus: integer("fallback_last_status"), fallbackLatencyMs: integer("fallback_latency_ms"), fallbackLastError: text("fallback_last_error"), selectedRoute: varchar("selected_route", { length: 12 }).default("unknown").notNull(), lastCheckedAt: timestamp("last_checked_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const schedulerLocks = pgTable("scheduler_locks", { name: varchar("name", { length: 80 }).primaryKey(), lockedUntil: timestamp("locked_until", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const epgSources = pgTable("epg_sources", { id: serial("id").primaryKey(), name: varchar("name", { length: 140 }).notNull(), feedUrl: text("feed_url"), status: epgStatus("status").default("inactive").notNull(), programmeCount: integer("programme_count").default(0).notNull(), lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }), lastAttemptAt: timestamp("last_attempt_at", { withTimezone: true }), lastError: text("last_error"), coverageEndsAt: timestamp("coverage_ends_at", { withTimezone: true }), refreshThresholdHours: integer("refresh_threshold_hours").default(6).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const epgProgrammes = pgTable("epg_programmes", { id: serial("id").primaryKey(), sourceId: integer("source_id").notNull(), channelEpgId: varchar("channel_epg_id", { length: 160 }).notNull(), title: varchar("title", { length: 255 }).notNull(), synopsis: text("synopsis"), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), ageRating: integer("age_rating").default(0).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() }, table => [uniqueIndex("epg_programmes_source_channel_start_unique").on(table.sourceId, table.channelEpgId, table.startsAt)]);

export const vodItems = pgTable("vod_items", { id: serial("id").primaryKey(), title: varchar("title", { length: 255 }).notNull(), kind: vodKind("kind").notNull(), tmdbId: integer("tmdb_id"), releaseYear: integer("release_year"), sourceUrl: text("source_url"), synopsis: text("synopsis"), posterUrl: text("poster_url"), ageRating: integer("age_rating").default(0).notNull(), status: vodStatus("status").default("draft").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const vodSeasons = pgTable("vod_seasons", { id: serial("id").primaryKey(), vodId: integer("vod_id").notNull(), seasonNumber: integer("season_number").notNull(), title: varchar("title", { length: 255 }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const vodEpisodes = pgTable("vod_episodes", { id: serial("id").primaryKey(), vodId: integer("vod_id").notNull(), seasonId: integer("season_id"), episodeNumber: integer("episode_number").notNull(), title: varchar("title", { length: 255 }).notNull(), sourceUrl: text("source_url").notNull(), publishedAt: timestamp("published_at", { withTimezone: true }).defaultNow().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });

export const pixCharges = pgTable("pix_charges", { id: serial("id").primaryKey(), customerId: integer("customer_id").notNull(), amountCents: integer("amount_cents").notNull(), status: pixStatus("status").default("pending").notNull(), providerPaymentId: varchar("provider_payment_id", { length: 120 }), externalReference: varchar("external_reference", { length: 160 }), requestedPlanId: integer("requested_plan_id"), requestedPlanCycleId: integer("requested_plan_cycle_id"), qrCode: text("qr_code"), qrCodeBase64: text("qr_code_base64"), dueAt: timestamp("due_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const integrationSettings = pgTable("integration_settings", { id: serial("id").primaryKey(), provider: varchar("provider", { length: 64 }).notNull().unique(), label: varchar("label", { length: 120 }).notNull(), baseUrl: varchar("base_url", { length: 500 }), enabled: boolean("enabled").default(false).notNull(), secretCiphertext: text("secret_ciphertext"), secretIv: varchar("secret_iv", { length: 48 }), secretTag: varchar("secret_tag", { length: 48 }), secretHint: varchar("secret_hint", { length: 8 }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });
export const androidReleases = pgTable("android_releases", { id: serial("id").primaryKey(), versionCode: integer("version_code").notNull().unique(), versionName: varchar("version_name", { length: 80 }).notNull(), apkUrl: text("apk_url").notNull(), apkSizeBytes: integer("apk_size_bytes").notNull(), sha256: varchar("sha256", { length: 64 }).notNull(), minimumSupportedVersionCode: integer("minimum_supported_version_code"), mandatory: boolean("mandatory").default(false).notNull(), releaseNotes: text("release_notes").notNull(), status: androidReleaseStatus("status").default("draft").notNull(), manifestSignature: text("manifest_signature"), signingKeyId: varchar("signing_key_id", { length: 80 }), publishedAt: timestamp("published_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(touch).notNull() });

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Plan = typeof plans.$inferSelect; export type PlanCycle = typeof planCycles.$inferSelect; export type Customer = typeof customers.$inferSelect; export type PlaybackSession = typeof playbackSessions.$inferSelect; export type Channel = typeof channels.$inferSelect; export type ChannelSource = typeof channelSources.$inferSelect; export type EpgSource = typeof epgSources.$inferSelect; export type EpgProgramme = typeof epgProgrammes.$inferSelect; export type VodItem = typeof vodItems.$inferSelect; export type VodSeason = typeof vodSeasons.$inferSelect; export type VodEpisode = typeof vodEpisodes.$inferSelect; export type PixCharge = typeof pixCharges.$inferSelect; export type IntegrationSetting = typeof integrationSettings.$inferSelect; export type AndroidRelease = typeof androidReleases.$inferSelect;
