export interface Env { VERCEL_API_BASE_URL: string; PLAYBACK_EDGE_RESOLVER_SECRET: string; }
type ResolvedPlayback = { ticket?: string; url: string; headers: Record<string, string> };
type ResolverError = { error?: { code?: string; message?: string; activeScreens?: number; screenLimit?: number; upgrade?: { action: string; procedure: string; label: string } } };
type ResolverResult = { status: number; playback?: ResolvedPlayback; error?: ResolverError };
export function proxyUrl(ticket: string, consumer: string, resource: string) { return `/media?ticket=${encodeURIComponent(ticket)}&consumer=${encodeURIComponent(consumer)}&resource=${encodeURIComponent(resource)}`; }
export function rewriteHlsManifest(manifest: string, ticket: string, consumer = "") { return manifest.split(/(\r?\n)/).map(line => { if (!line || /^\s*#EXT/.test(line)) return line.replace(/URI="([^"]+)"/g, (_match, uri) => `URI="${proxyUrl(ticket, consumer, uri)}"`); if (/^\s*#/.test(line)) return line; return proxyUrl(ticket, consumer, line.trim()); }).join(""); }
export async function consumerKeyHash(consumer: string) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(consumer)); return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join(""); }
	async function resolve(env: Env, ticket: string, consumer: string, resource?: string): Promise<ResolverResult> { const target = `${env.VERCEL_API_BASE_URL.replace(/\/$/, "")}/api/internal/playback/resolve`; const response = await fetch(target, { method: "POST", headers: { "content-type": "application/json", "x-videlis-playback-edge-secret": env.PLAYBACK_EDGE_RESOLVER_SECRET }, body: JSON.stringify({ ticket, consumerKeyHash: await consumerKeyHash(consumer), ...(resource ? { resource } : {}) }) }); if (!response.ok) return { status: response.status, error: await response.json<ResolverError>().catch(() => undefined) }; return { status: response.status, playback: await response.json<ResolvedPlayback>() }; }
export default { async fetch(request, env) { const url = new URL(request.url); if (request.method !== "GET" || url.pathname !== "/media") return new Response("Not found", { status: 404 }); const ticket = url.searchParams.get("ticket"); const consumer = url.searchParams.get("consumer"); if (!ticket || !consumer) return new Response("Unauthorized", { status: 401 }); const resolved = await resolve(env, ticket, consumer, url.searchParams.get("resource") || undefined); if (!resolved.playback) return new Response(JSON.stringify(resolved.error ?? { error: { code: "PLAYBACK_UNAUTHORIZED", message: "Reprodução não autorizada." } }), { status: resolved.status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" } }); const effectiveTicket = resolved.playback.ticket || ticket; const upstream = await fetch(resolved.playback.url, { headers: resolved.playback.headers, redirect: "follow" }); const contentType = upstream.headers.get("content-type") || "application/octet-stream"; if (/mpegurl|m3u8/i.test(contentType) || /\.m3u8(?:$|\?)/i.test(resolved.playback.url)) return new Response(rewriteHlsManifest(await upstream.text(), effectiveTicket, consumer), { status: upstream.status, headers: { "content-type": "application/vnd.apple.mpegurl", "cache-control": "no-store" } }); const headers = new Headers(); headers.set("content-type", contentType); headers.set("cache-control", "no-store"); const length = upstream.headers.get("content-length"); if (length) headers.set("content-length", length); return new Response(upstream.body, { status: upstream.status, headers }); } } satisfies ExportedHandler<Env>;
