import { useState } from "react";
import { KeyRound, LoaderCircle, LogIn } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function AdminLoginPage() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const login = trpc.auth.login.useMutation({ onSuccess: () => window.location.assign("/") });
  return <main className="grid min-h-screen place-items-center bg-[#091013] p-6 text-slate-100"><section className="surface-card w-full max-w-sm p-8"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl border border-[#43E6C2]/25 bg-[#43E6C2]/10"><img src="/storage/nexus-frequency-mark_5dbca578.png" alt="Videlis" className="h-7 w-7 object-contain" /></div><p className="mt-5 text-center font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-[#43E6C2]">Videlis</p><h1 className="mt-2 text-center text-2xl font-extrabold tracking-tight text-white">Login administrativo</h1><p className="mt-3 text-center text-sm leading-6 text-slate-400">Entre para acessar o centro de controle.</p><form className="mt-7 space-y-4" onSubmit={event => { event.preventDefault(); login.mutate({ username, password }); }}><label className="block"><span className="form-label">Usuário</span><input required autoComplete="username" value={username} onChange={event => setUsername(event.target.value)} className="form-input" placeholder="Seu usuário" /></label><label className="block"><span className="form-label">Senha</span><input required type="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} className="form-input" placeholder="Sua senha" /></label>{login.error ? <p role="alert" className="rounded-xl border border-rose-400/20 bg-rose-400/[.07] px-3 py-2 text-xs text-rose-200">Usuário ou senha inválidos.</p> : null}<button disabled={login.isPending} type="submit" className="pressable inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#43E6C2] px-4 py-3 text-sm font-bold text-[#07201c] disabled:cursor-not-allowed disabled:opacity-60">{login.isPending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <LogIn className="h-4 w-4" />}{login.isPending ? "Entrando..." : "Entrar"}</button></form><p className="mt-5 flex items-center justify-center gap-2 text-[11px] text-slate-500"><KeyRound className="h-3.5 w-3.5" /> Acesso restrito ao administrador</p></section></main>;
}
