import { useMemo, useState } from "react";
import { Copy, KeyRound, ListVideo } from "lucide-react";
import { toast } from "sonner";
import PanelLayout from "@/components/PanelLayout";

export default function M3uPage() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const cleanedUsername = username.replace(/\D/g, "");
  const cleanedPassword = password.replace(/\D/g, "");
  const url = useMemo(() => cleanedUsername && cleanedPassword ? `${window.location.origin}/get.php?username=${encodeURIComponent(cleanedUsername)}&password=${encodeURIComponent(cleanedPassword)}&type=m3u_plus&output=hls` : "", [cleanedUsername, cleanedPassword]);
  const apiUrl = useMemo(() => cleanedUsername && cleanedPassword ? `${window.location.origin}/player_api.php?username=${encodeURIComponent(cleanedUsername)}&password=${encodeURIComponent(cleanedPassword)}` : "", [cleanedUsername, cleanedPassword]);
  return <PanelLayout><section className="rounded-[26px] border border-white/[0.08] bg-[#10191f] p-6 sm:p-8"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[#43E6C2]/20 bg-[#43E6C2]/[.08]"><KeyRound className="h-4 w-4 text-[#43E6C2]" /></div><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#9df6df]">Compatibilidade Xtream V2</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.06em] text-white">Gerar lista M3U.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Informe o usuário e a senha numéricos do cliente. As mesmas credenciais autenticam a lista externa e o aplicativo oficial.</p></div></div><div className="mt-7 grid max-w-2xl gap-4 sm:grid-cols-2"><label className="form-label">Usuário Xtream<input inputMode="numeric" autoComplete="off" value={username} onChange={event => setUsername(event.target.value.replace(/\D/g, ""))} placeholder="Somente números" className="form-input mt-2 font-mono text-sm" /></label><label className="form-label">Senha Xtream<input inputMode="numeric" autoComplete="off" value={password} onChange={event => setPassword(event.target.value.replace(/\D/g, ""))} placeholder="Somente números" className="form-input mt-2 font-mono text-sm" /></label></div>{url ? <div className="mt-5 max-w-2xl rounded-2xl border border-[#43E6C2]/20 bg-[#43E6C2]/[0.05] p-4"><div className="flex items-center gap-2"><ListVideo className="h-4 w-4 text-[#43E6C2]" /><p className="text-sm font-bold text-slate-100">URLs Xtream prontas para copiar</p></div><p className="mt-4 font-mono text-[10px] uppercase tracking-[.14em] text-slate-500">Lista M3U</p><code className="mt-2 block break-all text-xs text-slate-300">{url}</code><p className="mt-4 font-mono text-[10px] uppercase tracking-[.14em] text-slate-500">API Xtream</p><code className="mt-2 block break-all text-xs text-slate-300">{apiUrl}</code><button type="button" onClick={async () => { await navigator.clipboard.writeText(url); toast.success("URL M3U copiada."); }} className="pressable mt-4 inline-flex items-center gap-2 rounded-xl bg-[#43E6C2] px-4 py-2.5 text-sm font-bold text-[#07201c]"><Copy className="h-4 w-4" /> Copiar URL M3U</button></div> : null}</section></PanelLayout>;
}
