import { createPrivateKey, sign } from "node:crypto";

export type AndroidReleaseManifestSource = { versionCode: number; versionName: string; apkUrl: string; apkSizeBytes: number; sha256: string; minimumSupportedVersionCode: number | null; mandatory: boolean; releaseNotes: string; publishedAt: Date | null; signingKeyId: string | null; manifestSignature: string | null };
export type AndroidUpdateManifest = { schemaVersion: 1; platform: "android"; versionCode: number; versionName: string; apkUrl: string; apkSizeBytes: number; sha256: string; minimumSupportedVersionCode: number | null; mandatory: boolean; releaseNotes: string; publishedAt: string | null; signingKeyId: string; signatureAlgorithm: "Ed25519"; manifestSignature: string };

export function canonicalAndroidManifest(release: AndroidReleaseManifestSource, signingKeyId: string) { return JSON.stringify({ schemaVersion: 1, platform: "android", versionCode: release.versionCode, versionName: release.versionName, apkUrl: release.apkUrl, apkSizeBytes: release.apkSizeBytes, sha256: release.sha256.toLowerCase(), minimumSupportedVersionCode: release.minimumSupportedVersionCode, mandatory: release.mandatory, releaseNotes: release.releaseNotes, publishedAt: release.publishedAt?.toISOString() ?? null, signingKeyId, signatureAlgorithm: "Ed25519" }); }
function privateKeyFromEnvironment(value: string) { return value.includes("BEGIN") ? createPrivateKey(value.replace(/\\n/g, "\n")) : createPrivateKey({ key: Buffer.from(value, "base64"), format: "der", type: "pkcs8" }); }
export function signAndroidManifest(release: AndroidReleaseManifestSource) { const privateKey = process.env.ANDROID_UPDATE_MANIFEST_PRIVATE_KEY; if (!privateKey) throw new Error("ANDROID_UPDATE_MANIFEST_PRIVATE_KEY deve ser configurada antes de publicar uma release Android."); const signingKeyId = process.env.ANDROID_UPDATE_MANIFEST_KEY_ID || "videlis-android-v1"; return { signingKeyId, manifestSignature: sign(null, Buffer.from(canonicalAndroidManifest(release, signingKeyId)), privateKeyFromEnvironment(privateKey)).toString("base64url") }; }
export function createAndroidUpdateManifest(release: AndroidReleaseManifestSource): AndroidUpdateManifest | undefined { if (!release.publishedAt || !release.signingKeyId || !release.manifestSignature) return undefined; return { schemaVersion: 1, platform: "android", versionCode: release.versionCode, versionName: release.versionName, apkUrl: release.apkUrl, apkSizeBytes: release.apkSizeBytes, sha256: release.sha256.toLowerCase(), minimumSupportedVersionCode: release.minimumSupportedVersionCode, mandatory: release.mandatory, releaseNotes: release.releaseNotes, publishedAt: release.publishedAt.toISOString(), signingKeyId: release.signingKeyId, signatureAlgorithm: "Ed25519", manifestSignature: release.manifestSignature }; }
export function androidUpdateDecision(release: AndroidUpdateManifest, installedVersionCode: number) { const available = release.versionCode > installedVersionCode; return { available, mandatory: available && (release.mandatory || (release.minimumSupportedVersionCode !== null && installedVersionCode < release.minimumSupportedVersionCode)), release: available ? release : null }; }
