import { afterEach, describe, expect, it, vi } from "vitest";
import gateway, { rewriteHlsManifest } from "../infrastructure/cloudflare-media-gateway/src/index";

const env = { VERCEL_API_BASE_URL: "https://api.videlis.exemplo/", PLAYBACK_EDGE_RESOLVER_SECRET: "edge-secret" };
describe("gateway Cloudflare de mídia", () => {
  afterEach(() => vi.restoreAllMocks());
  it("reescreve manifestos HLS e pede a origem apenas ao endpoint interno autenticado", async () => { const rewritten = rewriteHlsManifest("#EXTM3U\n#EXT-X-KEY:METHOD=AES-128,URI=\"key.bin\"\nsegment.ts", "ticket/1"); expect(rewritten).toContain("resource=key.bin"); expect(rewritten).toContain("resource=segment.ts"); const fetchMock = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(new Response(JSON.stringify({ url: "https://origin.exemplo/master.m3u8", headers: { Referer: "https://origin.exemplo" } }), { status: 200 })).mockResolvedValueOnce(new Response("#EXTM3U\nchunk.ts", { status: 200, headers: { "content-type": "application/vnd.apple.mpegurl" } })); const response = await gateway.fetch(new Request("https://media.videlis.exemplo/media?ticket=abc"), env as any, {} as ExecutionContext); expect(response.status).toBe(200); expect(await response.text()).toContain("resource=chunk.ts"); const resolverRequest = fetchMock.mock.calls[0][0] as string; expect(resolverRequest).toBe("https://api.videlis.exemplo/api/internal/playback/resolve"); expect((fetchMock.mock.calls[0][1] as RequestInit).headers).toMatchObject({ "x-videlis-playback-edge-secret": "edge-secret" }); });
  it("transmite mídia binária e propaga negação do resolvedor sem chamar a origem", async () => { const bytes = new Uint8Array([1, 2, 3, 4]); const fetchMock = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(new Response(JSON.stringify({ url: "https://origin.exemplo/filme.mkv", headers: {} }), { status: 200 })).mockResolvedValueOnce(new Response(bytes, { status: 200, headers: { "content-type": "video/x-matroska", "content-length": "4" } })); const binary = await gateway.fetch(new Request("https://media.videlis.exemplo/media?ticket=abc"), env as any, {} as ExecutionContext); expect(Array.from(new Uint8Array(await binary.arrayBuffer()))).toEqual([1, 2, 3, 4]); expect(binary.headers.get("content-type")).toBe("video/x-matroska"); vi.restoreAllMocks(); const deniedFetch = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(new Response(null, { status: 401 })); const denied = await gateway.fetch(new Request("https://media.videlis.exemplo/media?ticket=abc"), env as any, {} as ExecutionContext); expect(denied.status).toBe(401); expect(deniedFetch).toHaveBeenCalledTimes(1); });
});
