/** Acesso de dados PostgreSQL do Videlis, compatível com Neon. */
import { createHash, randomBytes, randomInt } from "node:crypto";
import { and, desc, eq, inArray, or, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import * as schema from "../drizzle/schema";
import { androidReleases, channelSources, channels, customerDevices, customers, epgProgrammes, epgSources, integrationSettings, playbackSessions, schedulerLocks, type InsertUser, planCycles, plans, pixCharges, users, vodEpisodes, vodItems, vodSeasons } from "../drizzle/schema";
import { ENV } from "./_core/env";
import { encryptIntegrationSecret } from "./integrationSecrets";
import { adminOpenId, verifyAdminPassword } from "./adminCredentials";
import { resolveNeonDatabaseUrl } from "./databaseUrl";

type Database = ReturnType<typeof drizzle<typeof schema>>;
let database: Database | null = null;

export async function getDb() {
  const connectionString = resolveNeonDatabaseUrl();
  if (!database && connectionString) database = drizzle(neon(connectionString), { schema });
  return database;
}

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb();
  if (!db) return;
  const values: InsertUser = { openId: user.openId, name: user.name ?? null, email: user.email ?? null, loginMethod: user.loginMethod ?? null, lastSignedIn: user.lastSignedIn ?? new Date(), role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user") };
  await db.insert(users).values(values).onConflictDoUpdate({ target: users.openId, set: { name: values.name, email: values.email, loginMethod: values.loginMethod, role: values.role, lastSignedIn: values.lastSignedIn } });
}

export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return rows[0]; }
export async function authenticateAdmin(username: string, password: string) {
  const db = await getDb();
  if (!db) throw new Error("Banco indisponível");
  const rows = await db.select().from(users).where(eq(users.openId, adminOpenId(username))).limit(1);
  const admin = rows[0];
  if (!admin || admin.role !== "admin" || !verifyAdminPassword(password, admin.passwordHash)) return undefined;
  await db.update(users).set({ lastSignedIn: new Date() }).where(eq(users.id, admin.id));
  return admin;
}
function hashAccessToken(value: string) { return createHash("sha256").update(value).digest("hex"); }
function randomDigits(length = 10) { return Array.from({ length }, () => randomInt(0, 10)).join(""); }
export function findAvailableDeviceSlot(screenLimit: number, occupiedSlots: readonly number[]) { const occupied = new Set(occupiedSlots); return Array.from({ length: screenLimit }, (_, index) => index + 1).find(candidate => !occupied.has(candidate)); }

async function createUniqueXtreamCredentials(db: NonNullable<Awaited<ReturnType<typeof getDb>>>) {
  for (let attempt = 0; attempt < 20; attempt += 1) {
    const username = randomDigits(10);
    const password = randomDigits(12);
    const passwordHash = hashAccessToken(password);
    const existing = await db.select({ id: customers.id }).from(customers).where(or(eq(customers.xtreamUsername, username), eq(customers.xtreamPasswordHash, passwordHash))).limit(1);
    if (!existing[0]) return { username, password, passwordHash };
  }
  throw new Error("Não foi possível reservar credenciais Xtream exclusivas. Tente novamente.");
}

export async function listCustomers() { const db = await getDb(); return db ? db.select().from(customers).orderBy(desc(customers.updatedAt)) : []; }
export async function createCustomer(input: { label: string; email?: string | null; phone?: string | null; planId: number; planCycleId: number }) {
  const db = await getDb(); if (!db) throw new Error("Banco indisponível");
  const [plan] = await db.select().from(plans).where(eq(plans.id, input.planId)).limit(1);
  const [cycle] = await db.select().from(planCycles).where(eq(planCycles.id, input.planCycleId)).limit(1);
  if (!plan || !cycle || cycle.planId !== plan.id || !plan.isActive || !cycle.isActive) throw new Error("Plano ou ciclo de pagamento inválido");
  const accessToken = randomBytes(24).toString("base64url"), xtream = await createUniqueXtreamCredentials(db), now = Date.now();
  const trialEndsAt = plan.trialDays > 0 ? new Date(now + plan.trialDays * 86_400_000) : null, expiresAt = new Date((trialEndsAt?.getTime() ?? now) + cycle.intervalDays * 86_400_000);
  await db.insert(customers).values({ label: input.label, email: input.email || null, phone: input.phone || null, plan: plan.name, planId: plan.id, planCycleId: cycle.id, screenLimit: plan.screenLimit, usedScreens: 0, expiresAt, trialEndsAt, accessTokenHash: hashAccessToken(accessToken), xtreamUsername: xtream.username, xtreamPasswordHash: xtream.passwordHash, status: "active" });
  return { accessToken, xtreamUsername: xtream.username, xtreamPassword: xtream.password };
}
export async function getCustomerById(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(customers).where(eq(customers.id, id)).limit(1); return rows[0]; }
export async function getCustomerByAccessToken(accessToken: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(customers).where(eq(customers.accessTokenHash, hashAccessToken(accessToken))).limit(1); return rows[0]; }
export async function getCustomerByXtreamCredentials(username: string, password: string) { const db = await getDb(); if (!db || !/^\d{6,16}$/.test(username) || !/^\d{6,32}$/.test(password)) return undefined; const rows = await db.select().from(customers).where(eq(customers.xtreamUsername, username)).limit(1); const customer = rows[0]; return customer?.xtreamPasswordHash === hashAccessToken(password) ? customer : undefined; }
export async function updateCustomerStatus(id: number, status: "active" | "attention" | "expired") { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.update(customers).set({ status }).where(eq(customers.id, id)); }
export async function updateCustomerProfile(input: { id: number; label: string; email?: string | null; phone?: string | null }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [updated] = await db.update(customers).set({ label: input.label, email: input.email || null, phone: input.phone || null }).where(eq(customers.id, input.id)).returning({ id: customers.id }); if (!updated) throw new Error("Cliente não encontrado"); }
export async function deleteCustomer(id: number) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [customer] = await db.select({ id: customers.id }).from(customers).where(eq(customers.id, id)).limit(1); if (!customer) throw new Error("Cliente não encontrado"); await db.delete(playbackSessions).where(eq(playbackSessions.customerId, id)); await db.delete(customerDevices).where(eq(customerDevices.customerId, id)); await db.delete(pixCharges).where(eq(pixCharges.customerId, id)); await db.delete(customers).where(eq(customers.id, id)); }
export async function rotateXtreamPassword(id: number) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); for (let attempt = 0; attempt < 20; attempt += 1) { const password = randomDigits(12); const passwordHash = hashAccessToken(password); const existing = await db.select({ id: customers.id }).from(customers).where(eq(customers.xtreamPasswordHash, passwordHash)).limit(1); if (!existing[0]) { await db.update(customers).set({ xtreamPasswordHash: passwordHash }).where(eq(customers.id, id)); return { password }; } } throw new Error("Não foi possível gerar uma senha Xtream exclusiva. Tente novamente."); }
export async function listCustomerDevices(customerId: number) { const db = await getDb(); return db ? db.select({ id: customerDevices.id, slot: customerDevices.slot, deviceName: customerDevices.deviceName, lastSeenAt: customerDevices.lastSeenAt, createdAt: customerDevices.createdAt }).from(customerDevices).where(eq(customerDevices.customerId, customerId)).orderBy(customerDevices.slot) : []; }
async function syncUsedScreens(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, customerId: number) { await db.execute(sql`UPDATE customers SET used_screens = (SELECT COUNT(*)::int FROM customer_devices WHERE customer_id = ${customerId}), updated_at = NOW() WHERE id = ${customerId}`); }
export async function registerCustomerDevice(input: { customerId: number; deviceName: string; deviceKey: string }, retry = false) {
  const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const deviceKeyHash = hashAccessToken(input.deviceKey);
  const customerRows = await db.select({ screenLimit: customers.screenLimit }).from(customers).where(eq(customers.id, input.customerId)).limit(1); const customer = customerRows[0]; if (!customer) throw new Error("Cliente não encontrado");
  const existing = await db.select({ id: customerDevices.id, slot: customerDevices.slot, deviceName: customerDevices.deviceName, lastSeenAt: customerDevices.lastSeenAt, createdAt: customerDevices.createdAt }).from(customerDevices).where(and(eq(customerDevices.customerId, input.customerId), eq(customerDevices.deviceKeyHash, deviceKeyHash))).limit(1);
  if (existing[0]) { await db.update(customerDevices).set({ deviceName: input.deviceName, lastSeenAt: new Date() }).where(eq(customerDevices.id, existing[0].id)); await syncUsedScreens(db, input.customerId); return { ...existing[0], deviceName: input.deviceName, lastSeenAt: new Date() }; }
  const devices = await listCustomerDevices(input.customerId); const slot = findAvailableDeviceSlot(customer.screenLimit, devices.map(device => device.slot));
  if (!slot) throw new Error("Limite de telas simultâneas atingido. Remova um dispositivo antes de continuar.");
  try { const [created] = await db.insert(customerDevices).values({ customerId: input.customerId, slot, deviceName: input.deviceName, deviceKeyHash, lastSeenAt: new Date() }).returning({ id: customerDevices.id, slot: customerDevices.slot, deviceName: customerDevices.deviceName, lastSeenAt: customerDevices.lastSeenAt, createdAt: customerDevices.createdAt }); if (!created) throw new Error("Não foi possível registrar o dispositivo"); await syncUsedScreens(db, input.customerId); return created; } catch (error) { if (!retry) return registerCustomerDevice(input, true); throw error; }
}
export async function removeCustomerDevice(input: { customerId: number; deviceId: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const removed = await db.delete(customerDevices).where(and(eq(customerDevices.id, input.deviceId), eq(customerDevices.customerId, input.customerId))).returning({ id: customerDevices.id }); if (!removed[0]) throw new Error("Dispositivo não encontrado para este cliente"); await syncUsedScreens(db, input.customerId); }
export type PlaybackSessionReservation = { allowed: boolean; activeSessions: number; screenLimit: number; expiresAt: Date | null };
/** Renova primeiro o consumidor já ativo; somente um novo consumidor disputa uma vaga global. */
export async function acquirePlaybackSession(input: { customerId: number; consumerKeyHash: string; leaseSeconds?: number }): Promise<PlaybackSessionReservation> {
  const db = await getDb(); if (!db) throw new Error("Banco indisponível");
  const leaseSeconds = Math.max(30, Math.min(900, input.leaseSeconds ?? 120));
  const result = await db.execute(sql`SELECT allowed, active_sessions, screen_limit, expires_at FROM videlis_acquire_playback_session(${input.customerId}, ${input.consumerKeyHash}, ${leaseSeconds})`);
  const rows = (result as unknown as { rows?: Array<{ allowed: boolean; active_sessions: number; screen_limit: number; expires_at: Date | string | null }> }).rows || [];
  const row = rows[0];
  if (!row) throw new Error("Não foi possível reservar a sessão de reprodução.");
  return { allowed: Boolean(row.allowed), activeSessions: Number(row.active_sessions), screenLimit: Number(row.screen_limit), expiresAt: row.expires_at ? new Date(row.expires_at) : null };
}
export async function listActivePlaybackSessions(customerId: number) { const db = await getDb(); if (!db) return []; return db.select({ id: playbackSessions.id, expiresAt: playbackSessions.expiresAt, lastSeenAt: playbackSessions.lastSeenAt }).from(playbackSessions).where(and(eq(playbackSessions.customerId, customerId), sql`${playbackSessions.expiresAt} > NOW()`)).orderBy(desc(playbackSessions.lastSeenAt)); }
export async function terminatePlaybackSession(input: { customerId: number; sessionId: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const removed = await db.delete(playbackSessions).where(and(eq(playbackSessions.id, input.sessionId), eq(playbackSessions.customerId, input.customerId))).returning({ id: playbackSessions.id }); if (!removed[0]) throw new Error("Sessão de reprodução não encontrada"); }

export async function listChannels() { const db = await getDb(); return db ? db.select().from(channels).orderBy(desc(channels.updatedAt)) : []; }
export async function createChannel(input: { name: string; groupTitle: string; channelNumber: number; epgId?: string | null; logoUrl?: string | null; ageRating: number; sources: Array<{ quality: string; primaryUrl: string; primaryOrigin?: string | null; primaryReferer?: string | null; fallbackUrl?: string | null; fallbackOrigin?: string | null; fallbackReferer?: string | null }> }) {
  const db = await getDb(); if (!db) throw new Error("Banco indisponível");
  const qualities = input.sources.map(source => source.quality).join(" · ");
  const [inserted] = await db.insert(channels).values({ channelNumber: input.channelNumber, name: input.name, groupTitle: input.groupTitle, epgId: input.epgId || null, logoUrl: input.logoUrl || null, ageRating: input.ageRating, qualities, routeCount: input.sources.length, isActive: false }).returning({ id: channels.id });
  if (!inserted) throw new Error("Não foi possível criar o canal");
  await db.insert(channelSources).values(input.sources.map(source => ({ channelId: inserted.id, quality: source.quality, primaryUrl: source.primaryUrl, primaryOrigin: source.primaryOrigin || null, primaryReferer: source.primaryReferer || null, fallbackUrl: source.fallbackUrl || null, fallbackOrigin: source.fallbackOrigin || null, fallbackReferer: source.fallbackReferer || null })));
  return inserted;
}
export async function getChannelSources(channelId: number) { const db = await getDb(); return db ? db.select().from(channelSources).where(eq(channelSources.channelId, channelId)) : []; }
export async function listChannelSourcesForMonitor() { const db = await getDb(); return db ? db.select().from(channelSources).orderBy(channelSources.id) : []; }
export async function saveChannelSourceHealth(input: { id: number; selectedRoute: "primary" | "fallback" | "unavailable"; primary: { status: number | null; latencyMs: number; error?: string }; fallback?: { status: number | null; latencyMs: number; error?: string } }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.update(channelSources).set({ primaryLastStatus: input.primary.status, primaryLatencyMs: input.primary.latencyMs, primaryLastError: input.primary.error ?? null, fallbackLastStatus: input.fallback?.status ?? null, fallbackLatencyMs: input.fallback?.latencyMs ?? null, fallbackLastError: input.fallback?.error ?? null, selectedRoute: input.selectedRoute, lastCheckedAt: new Date() }).where(eq(channelSources.id, input.id)); }
export async function saveChannelHealth(input: { channelId: number; healthStatus: "healthy" | "fallback" | "unavailable"; healthMessage?: string | null }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.update(channels).set({ healthStatus: input.healthStatus, healthMessage: input.healthMessage ?? null, lastHealthAt: new Date() }).where(eq(channels.id, input.channelId)); }
export async function tryAcquireSchedulerLock(name: string, leaseMilliseconds: number) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const now = new Date(); const lockedUntil = new Date(now.getTime() + leaseMilliseconds); const result = await db.execute(sql`INSERT INTO scheduler_locks (name, locked_until, updated_at) VALUES (${name}, ${lockedUntil}, NOW()) ON CONFLICT (name) DO UPDATE SET locked_until = EXCLUDED.locked_until, updated_at = NOW() WHERE scheduler_locks.locked_until <= ${now} RETURNING name`); return Array.isArray((result as { rows?: unknown[] }).rows) && Boolean((result as { rows?: unknown[] }).rows?.length); }
export async function releaseSchedulerLock(name: string) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.update(schedulerLocks).set({ lockedUntil: new Date(0) }).where(eq(schedulerLocks.name, name)); }
export async function toggleChannel(id: number, isActive: boolean) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.update(channels).set({ isActive }).where(eq(channels.id, id)); }
export async function updateChannel(input: { id: number; name: string; groupTitle: string; channelNumber: number; epgId?: string | null; logoUrl?: string | null; ageRating: number; sources: Array<{ quality: string; primaryUrl: string; primaryOrigin?: string | null; primaryReferer?: string | null; fallbackUrl?: string | null; fallbackOrigin?: string | null; fallbackReferer?: string | null }> }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [updated] = await db.update(channels).set({ channelNumber: input.channelNumber, name: input.name, groupTitle: input.groupTitle, epgId: input.epgId || null, logoUrl: input.logoUrl || null, ageRating: input.ageRating, qualities: input.sources.map(source => source.quality).join(" · "), routeCount: input.sources.length, healthStatus: "unknown", healthMessage: null, lastHealthAt: null }).where(eq(channels.id, input.id)).returning({ id: channels.id }); if (!updated) throw new Error("Canal não encontrado"); await db.delete(channelSources).where(eq(channelSources.channelId, input.id)); await db.insert(channelSources).values(input.sources.map(source => ({ channelId: input.id, quality: source.quality, primaryUrl: source.primaryUrl, primaryOrigin: source.primaryOrigin || null, primaryReferer: source.primaryReferer || null, fallbackUrl: source.fallbackUrl || null, fallbackOrigin: source.fallbackOrigin || null, fallbackReferer: source.fallbackReferer || null }))); }
export async function deleteChannel(id: number) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [channel] = await db.select({ id: channels.id }).from(channels).where(eq(channels.id, id)).limit(1); if (!channel) throw new Error("Canal não encontrado"); await db.delete(channelSources).where(eq(channelSources.channelId, id)); await db.delete(channels).where(eq(channels.id, id)); }

export async function listEpgSources() { const db = await getDb(); return db ? db.select().from(epgSources).orderBy(desc(epgSources.updatedAt)) : []; }
export async function createEpgSource(input: { name: string; feedUrl: string; refreshThresholdHours: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.insert(epgSources).values({ ...input, status: "inactive" }); }
export async function updateEpgSource(input: { id: number; name: string; feedUrl: string; refreshThresholdHours: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [updated] = await db.update(epgSources).set({ name: input.name, feedUrl: input.feedUrl, refreshThresholdHours: input.refreshThresholdHours, status: "inactive", lastError: null }).where(eq(epgSources.id, input.id)).returning({ id: epgSources.id }); if (!updated) throw new Error("Fonte EPG não encontrada"); }
export async function deleteEpgSource(id: number) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [source] = await db.select({ id: epgSources.id }).from(epgSources).where(eq(epgSources.id, id)).limit(1); if (!source) throw new Error("Fonte EPG não encontrada"); await db.delete(epgProgrammes).where(eq(epgProgrammes.sourceId, id)); await db.delete(epgSources).where(eq(epgSources.id, id)); }
export async function getEpgSourceById(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(epgSources).where(eq(epgSources.id, id)).limit(1); return rows[0]; }
export async function saveEpgSyncSuccess(input: { id: number; programmeCount: number; coverageEndsAt: Date }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const now = new Date(); await db.update(epgSources).set({ status: "healthy", programmeCount: input.programmeCount, coverageEndsAt: input.coverageEndsAt, lastSyncedAt: now, lastAttemptAt: now, lastError: null }).where(eq(epgSources.id, input.id)); }
export async function saveEpgSyncFailure(id: number, message: string) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.update(epgSources).set({ status: "attention", lastAttemptAt: new Date(), lastError: message.slice(0, 2000) }).where(eq(epgSources.id, id)); }
export async function replaceEpgProgrammes(sourceId: number, programmes: Array<{ channelEpgId: string; title: string; synopsis?: string | null; startsAt: Date; endsAt: Date; ageRating: number }>) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.delete(epgProgrammes).where(eq(epgProgrammes.sourceId, sourceId)); if (programmes.length) await db.insert(epgProgrammes).values(programmes.map(programme => ({ ...programme, sourceId }))); }
export async function listEpgProgrammes(channelEpgIds: string[], now = new Date()) { const db = await getDb(); if (!db || !channelEpgIds.length) return []; return db.select().from(epgProgrammes).where(and(inArray(epgProgrammes.channelEpgId, channelEpgIds), sql`${epgProgrammes.endsAt} > ${now}`)).orderBy(epgProgrammes.startsAt); }

export async function listVodItems() { const db = await getDb(); return db ? db.select().from(vodItems).orderBy(desc(vodItems.updatedAt)) : []; }
export async function getVodItemById(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(vodItems).where(eq(vodItems.id, id)).limit(1); return rows[0]; }
export async function getVodEpisodeById(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(vodEpisodes).where(eq(vodEpisodes.id, id)).limit(1); return rows[0]; }
export async function createVodItem(input: { title: string; kind: "filme" | "serie" | "novela"; tmdbId?: number | null; releaseYear?: number | null; sourceUrl?: string | null; synopsis?: string | null; posterUrl?: string | null; ageRating?: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.insert(vodItems).values({ ...input, status: input.sourceUrl ? "ready" : "draft" }); }
export async function updateVodItem(input: { id: number; title: string; kind: "filme" | "serie" | "novela"; tmdbId?: number | null; releaseYear?: number | null; sourceUrl?: string | null; synopsis?: string | null; posterUrl?: string | null; ageRating?: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [updated] = await db.update(vodItems).set({ title: input.title, kind: input.kind, tmdbId: input.tmdbId ?? null, releaseYear: input.releaseYear ?? null, sourceUrl: input.sourceUrl ?? null, synopsis: input.synopsis ?? null, posterUrl: input.posterUrl ?? null, ageRating: input.ageRating ?? 0, status: input.sourceUrl ? "ready" : "draft" }).where(eq(vodItems.id, input.id)).returning({ id: vodItems.id }); if (!updated) throw new Error("VOD não encontrado"); }
export async function deleteVodItem(id: number) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [item] = await db.select({ id: vodItems.id }).from(vodItems).where(eq(vodItems.id, id)).limit(1); if (!item) throw new Error("VOD não encontrado"); await db.delete(vodEpisodes).where(eq(vodEpisodes.vodId, id)); await db.delete(vodSeasons).where(eq(vodSeasons.vodId, id)); await db.delete(vodItems).where(eq(vodItems.id, id)); }
export async function updateVodSeason(input: { id: number; vodId: number; seasonNumber: number; title?: string | null }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [updated] = await db.update(vodSeasons).set({ seasonNumber: input.seasonNumber, title: input.title ?? null }).where(and(eq(vodSeasons.id, input.id), eq(vodSeasons.vodId, input.vodId))).returning({ id: vodSeasons.id }); if (!updated) throw new Error("Temporada não encontrada"); }
export async function deleteVodSeason(input: { id: number; vodId: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [season] = await db.select({ id: vodSeasons.id }).from(vodSeasons).where(and(eq(vodSeasons.id, input.id), eq(vodSeasons.vodId, input.vodId))).limit(1); if (!season) throw new Error("Temporada não encontrada"); await db.update(vodEpisodes).set({ seasonId: null }).where(eq(vodEpisodes.seasonId, input.id)); await db.delete(vodSeasons).where(eq(vodSeasons.id, input.id)); }
export async function updateVodEpisode(input: { id: number; vodId: number; seasonId?: number | null; episodeNumber: number; title: string; sourceUrl: string }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [updated] = await db.update(vodEpisodes).set({ seasonId: input.seasonId ?? null, episodeNumber: input.episodeNumber, title: input.title, sourceUrl: input.sourceUrl }).where(and(eq(vodEpisodes.id, input.id), eq(vodEpisodes.vodId, input.vodId))).returning({ id: vodEpisodes.id }); if (!updated) throw new Error("Episódio não encontrado"); }
export async function deleteVodEpisode(input: { id: number; vodId: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const removed = await db.delete(vodEpisodes).where(and(eq(vodEpisodes.id, input.id), eq(vodEpisodes.vodId, input.vodId))).returning({ id: vodEpisodes.id }); if (!removed[0]) throw new Error("Episódio não encontrado"); }

export async function listIntegrationSettings() { const db = await getDb(); if (!db) return []; const rows = await db.select().from(integrationSettings).orderBy(desc(integrationSettings.updatedAt)); return rows.map(({ secretCiphertext: _secretCiphertext, secretIv: _secretIv, secretTag: _secretTag, ...safe }) => safe); }
export async function getPrivateIntegrationSetting(provider: "mercado_pago" | "vod_metadata") { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(integrationSettings).where(eq(integrationSettings.provider, provider)).limit(1); return rows[0]; }
export async function saveIntegrationSetting(input: { provider: string; label: string; baseUrl?: string | null; enabled: boolean; secret?: string | null }) {
  const db = await getDb(); if (!db) throw new Error("Banco indisponível");
  const encrypted = input.secret ? encryptIntegrationSecret(input.secret) : null;
  const values = { provider: input.provider, label: input.label, baseUrl: input.baseUrl ?? null, enabled: input.enabled, ...(encrypted ? { secretCiphertext: encrypted.ciphertext, secretIv: encrypted.iv, secretTag: encrypted.tag, secretHint: encrypted.hint } : {}) };
  await db.insert(integrationSettings).values(values).onConflictDoUpdate({ target: integrationSettings.provider, set: { label: values.label, baseUrl: values.baseUrl, enabled: values.enabled, ...(encrypted ? { secretCiphertext: encrypted.ciphertext, secretIv: encrypted.iv, secretTag: encrypted.tag, secretHint: encrypted.hint } : {}) } });
}

export type AndroidReleaseInput = { versionCode: number; versionName: string; apkUrl: string; apkSizeBytes: number; sha256: string; minimumSupportedVersionCode?: number | null; mandatory: boolean; releaseNotes: string };
export async function listAndroidReleases() { const db = await getDb(); return db ? db.select().from(androidReleases).orderBy(desc(androidReleases.versionCode)) : []; }
export async function getAndroidReleaseById(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(androidReleases).where(eq(androidReleases.id, id)).limit(1); return rows[0]; }
export async function getLatestPublishedAndroidRelease() { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(androidReleases).where(eq(androidReleases.status, "published")).orderBy(desc(androidReleases.versionCode)).limit(1); return rows[0]; }
export async function createAndroidRelease(input: AndroidReleaseInput) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [release] = await db.insert(androidReleases).values({ ...input, minimumSupportedVersionCode: input.minimumSupportedVersionCode ?? null, sha256: input.sha256.toLowerCase(), status: "draft" }).returning({ id: androidReleases.id }); return release; }
export async function updateAndroidRelease(input: AndroidReleaseInput & { id: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [release] = await db.update(androidReleases).set({ versionCode: input.versionCode, versionName: input.versionName, apkUrl: input.apkUrl, apkSizeBytes: input.apkSizeBytes, sha256: input.sha256.toLowerCase(), minimumSupportedVersionCode: input.minimumSupportedVersionCode ?? null, mandatory: input.mandatory, releaseNotes: input.releaseNotes, status: "draft", manifestSignature: null, signingKeyId: null, publishedAt: null }).where(eq(androidReleases.id, input.id)).returning({ id: androidReleases.id }); if (!release) throw new Error("Release Android não encontrada"); }
export async function deleteAndroidRelease(id: number) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const removed = await db.delete(androidReleases).where(eq(androidReleases.id, id)).returning({ id: androidReleases.id }); if (!removed[0]) throw new Error("Release Android não encontrada"); }
export async function publishAndroidRelease(input: { id: number; manifestSignature: string; signingKeyId: string }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [release] = await db.update(androidReleases).set({ status: "published", manifestSignature: input.manifestSignature, signingKeyId: input.signingKeyId, publishedAt: new Date() }).where(eq(androidReleases.id, input.id)).returning({ id: androidReleases.id }); if (!release) throw new Error("Release Android não encontrada"); await db.update(androidReleases).set({ status: "archived" }).where(and(sql`${androidReleases.id} <> ${input.id}`, eq(androidReleases.status, "published"))); return release; }
export async function archiveAndroidRelease(id: number) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.update(androidReleases).set({ status: "archived" }).where(eq(androidReleases.id, id)); }

export async function createPixCharge(input: { customerId: number; amountCents: number; providerPaymentId: string; externalReference: string; requestedPlanId?: number | null; requestedPlanCycleId?: number | null; qrCode: string | null; qrCodeBase64: string | null; dueAt: Date }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.insert(pixCharges).values({ ...input, status: "pending" }); }
export async function listPixChargesForCustomer(customerId: number) { const db = await getDb(); return db ? db.select().from(pixCharges).where(eq(pixCharges.customerId, customerId)).orderBy(desc(pixCharges.createdAt)) : []; }
export async function updatePixChargeStatusByProviderId(providerPaymentId: string, status: "pending" | "approved" | "expired" | "cancelled") { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.update(pixCharges).set({ status }).where(eq(pixCharges.providerPaymentId, providerPaymentId)); }
/** Atualiza a cobrança e reivindica uma alteração de plano somente uma vez quando o PIX é aprovado. */
export async function settlePixCharge(providerPaymentId: string, status: "pending" | "approved" | "expired" | "cancelled") {
  const db = await getDb(); if (!db) throw new Error("Banco indisponível");
  if (status !== "approved") { await db.update(pixCharges).set({ status }).where(eq(pixCharges.providerPaymentId, providerPaymentId)); return { appliedPlanChange: false }; }
  const [charge] = await db.select().from(pixCharges).where(eq(pixCharges.providerPaymentId, providerPaymentId)).limit(1);
  if (!charge) return { appliedPlanChange: false };
  if (!charge.requestedPlanId || !charge.requestedPlanCycleId) { await db.update(pixCharges).set({ status: "approved" }).where(eq(pixCharges.providerPaymentId, providerPaymentId)); return { appliedPlanChange: false }; }
  const claimed = await db.update(pixCharges).set({ status: "approved", requestedPlanId: null, requestedPlanCycleId: null }).where(and(eq(pixCharges.providerPaymentId, providerPaymentId), eq(pixCharges.status, "pending"))).returning({ id: pixCharges.id });
  if (!claimed[0]) return { appliedPlanChange: false };
  await applyCustomerPlanChange({ customerId: charge.customerId, planId: charge.requestedPlanId, planCycleId: charge.requestedPlanCycleId });
  return { appliedPlanChange: true };
}

export async function listPlans() { const db = await getDb(); if (!db) return []; const base = await db.select().from(plans).orderBy(desc(plans.updatedAt)); const cycles = await db.select().from(planCycles).orderBy(planCycles.intervalDays); return base.map(plan => ({ ...plan, cycles: cycles.filter(cycle => cycle.planId === plan.id) })); }
export async function createPlan(input: { name: string; monthlyPriceCents: number; screenLimit: number; trialDays: number; cycles: Array<{ cycle: "monthly" | "quarterly" | "semiannual" | "annual" | "custom"; intervalDays: number; discountPercent: number }> }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [inserted] = await db.insert(plans).values({ name: input.name, monthlyPriceCents: input.monthlyPriceCents, screenLimit: input.screenLimit, trialDays: input.trialDays, isActive: true }).returning({ id: plans.id }); if (!inserted) throw new Error("Não foi possível criar o plano"); await db.insert(planCycles).values(input.cycles.map(cycle => ({ ...cycle, planId: inserted.id, isActive: true }))); return inserted; }
export async function updatePlan(input: { id: number; name: string; monthlyPriceCents: number; screenLimit: number; trialDays: number; cycles: Array<{ id?: number; cycle: "monthly" | "quarterly" | "semiannual" | "annual" | "custom"; intervalDays: number; discountPercent: number }> }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [updated] = await db.update(plans).set({ name: input.name, monthlyPriceCents: input.monthlyPriceCents, screenLimit: input.screenLimit, trialDays: input.trialDays }).where(eq(plans.id, input.id)).returning({ id: plans.id }); if (!updated) throw new Error("Plano não encontrado"); for (const cycle of input.cycles) { if (cycle.id) { await db.update(planCycles).set({ cycle: cycle.cycle, intervalDays: cycle.intervalDays, discountPercent: cycle.discountPercent, isActive: true }).where(and(eq(planCycles.id, cycle.id), eq(planCycles.planId, input.id))); } else { await db.insert(planCycles).values({ planId: input.id, cycle: cycle.cycle, intervalDays: cycle.intervalDays, discountPercent: cycle.discountPercent, isActive: true }); } } }
export async function deletePlan(id: number) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const linked = await db.select({ id: customers.id }).from(customers).where(eq(customers.planId, id)).limit(1); if (linked[0]) throw new Error("Não é possível excluir um plano vinculado a clientes. Desative-o ou altere os clientes primeiro."); const [plan] = await db.select({ id: plans.id }).from(plans).where(eq(plans.id, id)).limit(1); if (!plan) throw new Error("Plano não encontrado"); await db.delete(planCycles).where(eq(planCycles.planId, id)); await db.delete(plans).where(eq(plans.id, id)); }
export async function getPlanCycle(planCycleId: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(planCycles).where(eq(planCycles.id, planCycleId)).limit(1); return rows[0]; }
export async function applyCustomerPlanChange(input: { customerId: number; planId: number; planCycleId: number }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const [plan] = await db.select().from(plans).where(eq(plans.id, input.planId)).limit(1); const [cycle] = await db.select().from(planCycles).where(eq(planCycles.id, input.planCycleId)).limit(1); if (!plan || !cycle || cycle.planId !== plan.id || !plan.isActive || !cycle.isActive) throw new Error("Plano ou ciclo de pagamento inválido"); const expiresAt = new Date(Date.now() + cycle.intervalDays * 86_400_000); await db.update(customers).set({ plan: plan.name, planId: plan.id, planCycleId: cycle.id, screenLimit: plan.screenLimit, expiresAt, trialEndsAt: null, status: "active" }).where(eq(customers.id, input.customerId)); return { plan, cycle, expiresAt }; }

export async function listVodSeasons(vodId: number) { const db = await getDb(); return db ? db.select().from(vodSeasons).where(eq(vodSeasons.vodId, vodId)).orderBy(vodSeasons.seasonNumber) : []; }
export async function listVodEpisodes(vodId: number) { const db = await getDb(); return db ? db.select().from(vodEpisodes).where(eq(vodEpisodes.vodId, vodId)).orderBy(desc(vodEpisodes.publishedAt), desc(vodEpisodes.episodeNumber)) : []; }
export async function createVodSeason(input: { vodId: number; seasonNumber: number; title?: string | null }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.insert(vodSeasons).values(input); }
export async function createVodEpisode(input: { vodId: number; seasonId?: number | null; episodeNumber: number; title: string; sourceUrl: string }) { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); await db.insert(vodEpisodes).values(input); }
