import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ getChannelSources: vi.fn(), getVodItemById: vi.fn(), getVodEpisodeById: vi.fn(), readPlaybackTicket: vi.fn() }));
vi.mock("./db", () => ({ getChannelSources: mocks.getChannelSources, getVodItemById: mocks.getVodItemById, getVodEpisodeById: mocks.getVodEpisodeById }));
vi.mock("./playbackTickets", () => ({ readPlaybackTicket: mocks.readPlaybackTicket }));
import { registerPlaybackResolverRoutes } from "./playbackResolverRoutes";

function response() { const result: any = { status: vi.fn(), json: vi.fn(), sendStatus: vi.fn() }; result.status.mockReturnValue(result); return result; }
function handler() { const app = { post: vi.fn() }; registerPlaybackResolverRoutes(app as any); return app.post.mock.calls[0][1] as (req: any, res: any) => Promise<void>; }
function request(body: Record<string, unknown>, secret = "resolver-test-secret") { return { body, get: (header: string) => header === "x-videlis-playback-edge-secret" ? secret : undefined }; }

describe("resolvedor interno de reprodução", () => {
  beforeEach(() => { vi.clearAllMocks(); process.env.PLAYBACK_EDGE_RESOLVER_SECRET = "resolver-test-secret"; });
  it("nega gateway sem segredo válido e tickets inválidos", async () => { const route = handler(); const unauthenticated = response(); await route(request({ ticket: "x" }, "outro"), unauthenticated); expect(unauthenticated.sendStatus).toHaveBeenCalledWith(401); mocks.readPlaybackTicket.mockResolvedValue(undefined); const invalid = response(); await route(request({ ticket: "x" }), invalid); expect(invalid.status).toHaveBeenCalledWith(401); expect(mocks.getChannelSources).not.toHaveBeenCalled(); });
  it("resolve canal selecionado com headers privados e recusa recurso externo", async () => { const route = handler(); mocks.readPlaybackTicket.mockResolvedValue({ resource: "channel", itemId: 7, quality: "FHD" }); mocks.getChannelSources.mockResolvedValue([{ quality: "FHD", selectedRoute: "fallback", primaryUrl: "https://primary.exemplo/canal.m3u8", primaryOrigin: "https://primary.exemplo", primaryReferer: null, fallbackUrl: "https://fallback.exemplo/canal.m3u8", fallbackOrigin: "https://fallback.exemplo", fallbackReferer: "https://fallback.exemplo/app" }]); const ok = response(); await route(request({ ticket: "ok" }), ok); expect(ok.json).toHaveBeenCalledWith({ url: "https://fallback.exemplo/canal.m3u8", headers: { Origin: "https://fallback.exemplo", Referer: "https://fallback.exemplo/app", "User-Agent": "VidelisMediaGateway/1.0" } }); const external = response(); await route(request({ ticket: "ok", resource: "https://fora.exemplo/segment.ts" }), external); expect(external.status).toHaveBeenCalledWith(400); });
  it("resolve filme e episódio sem devolver credenciais ou URL ao cliente", async () => { const route = handler(); mocks.readPlaybackTicket.mockResolvedValueOnce({ resource: "vod", itemId: 9 }).mockResolvedValueOnce({ resource: "episode", itemId: 10 }); mocks.getVodItemById.mockResolvedValue({ sourceUrl: "https://vod.exemplo/filme.mkv" }); mocks.getVodEpisodeById.mockResolvedValue({ sourceUrl: "https://vod.exemplo/episodio.m3u8" }); const movie = response(); const episode = response(); await route(request({ ticket: "movie" }), movie); await route(request({ ticket: "episode" }), episode); expect(movie.json).toHaveBeenCalledWith(expect.objectContaining({ url: "https://vod.exemplo/filme.mkv" })); expect(episode.json).toHaveBeenCalledWith(expect.objectContaining({ url: "https://vod.exemplo/episodio.m3u8" })); });
});
