import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ acquirePlaybackSession: vi.fn(), createPlaybackTicket: vi.fn(), getChannelSources: vi.fn(), getVodItemById: vi.fn(), getVodEpisodeById: vi.fn(), readPlaybackTicket: vi.fn() }));
vi.mock("./db", () => ({ acquirePlaybackSession: mocks.acquirePlaybackSession, getChannelSources: mocks.getChannelSources, getVodItemById: mocks.getVodItemById, getVodEpisodeById: mocks.getVodEpisodeById }));
vi.mock("./playbackTickets", () => ({ createPlaybackTicket: mocks.createPlaybackTicket, readPlaybackTicket: mocks.readPlaybackTicket }));
import { registerPlaybackResolverRoutes } from "./playbackResolverRoutes";

function response() { const result: any = { status: vi.fn(), json: vi.fn(), sendStatus: vi.fn() }; result.status.mockReturnValue(result); return result; }
function handler() { const app = { post: vi.fn() }; registerPlaybackResolverRoutes(app as any); return app.post.mock.calls[0][1] as (req: any, res: any) => Promise<void>; }
const consumerKeyHash = "a".repeat(64);
function ticket(resource: "channel" | "vod" | "episode", itemId: number) { return { resource, itemId, customerId: 7, consumerKeyHash }; }
function request(body: Record<string, unknown>, secret = "resolver-test-secret") { return { body: { consumerKeyHash, ...body }, get: (header: string) => header === "x-videlis-playback-edge-secret" ? secret : undefined }; }

describe("resolvedor interno de reprodução", () => {
  beforeEach(() => { vi.clearAllMocks(); process.env.PLAYBACK_EDGE_RESOLVER_SECRET = "resolver-test-secret"; mocks.acquirePlaybackSession.mockResolvedValue({ allowed: true, activeSessions: 1, expiresAt: new Date(Date.now() + 120_000) }); mocks.createPlaybackTicket.mockResolvedValue("ticket-renovado"); });
  it("nega gateway sem segredo válido e tickets inválidos", async () => { const route = handler(); const unauthenticated = response(); await route(request({ ticket: "x" }, "outro"), unauthenticated); expect(unauthenticated.sendStatus).toHaveBeenCalledWith(401); mocks.readPlaybackTicket.mockResolvedValue(undefined); const invalid = response(); await route(request({ ticket: "x" }), invalid); expect(invalid.status).toHaveBeenCalledWith(401); expect(mocks.getChannelSources).not.toHaveBeenCalled(); });
  it("resolve canal selecionado após reservar a tela global, renova ticket e recusa recurso externo", async () => { const route = handler(); mocks.readPlaybackTicket.mockResolvedValue({ ...ticket("channel", 7), quality: "FHD" }); mocks.getChannelSources.mockResolvedValue([{ quality: "FHD", selectedRoute: "fallback", primaryUrl: "https://primary.exemplo/canal.m3u8", primaryOrigin: "https://primary.exemplo", primaryReferer: null, fallbackUrl: "https://fallback.exemplo/canal.m3u8", fallbackOrigin: "https://fallback.exemplo", fallbackReferer: "https://fallback.exemplo/app" }]); const ok = response(); await route(request({ ticket: "ok" }), ok); expect(mocks.acquirePlaybackSession).toHaveBeenCalledWith({ customerId: 7, consumerKeyHash }); expect(ok.json).toHaveBeenCalledWith({ ticket: "ticket-renovado", url: "https://fallback.exemplo/canal.m3u8", headers: { Origin: "https://fallback.exemplo", Referer: "https://fallback.exemplo/app", "User-Agent": "VidelisMediaGateway/1.0" } }); const external = response(); await route(request({ ticket: "ok", resource: "https://fora.exemplo/segment.ts" }), external); expect(external.status).toHaveBeenCalledWith(400); });
  it("compartilha uma única reserva global entre canal, filme e episódio do mesmo consumidor", async () => { const route = handler(); mocks.readPlaybackTicket.mockResolvedValueOnce(ticket("channel", 7)).mockResolvedValueOnce(ticket("vod", 9)).mockResolvedValueOnce(ticket("episode", 10)); mocks.getChannelSources.mockResolvedValue([{ quality: "AUTO", selectedRoute: "primary", primaryUrl: "https://live.exemplo/canal.m3u8", primaryOrigin: null, primaryReferer: null, fallbackUrl: null }]); mocks.getVodItemById.mockResolvedValue({ sourceUrl: "https://vod.exemplo/filme.mkv" }); mocks.getVodEpisodeById.mockResolvedValue({ sourceUrl: "https://vod.exemplo/episodio.m3u8" }); await route(request({ ticket: "live" }), response()); await route(request({ ticket: "movie" }), response()); await route(request({ ticket: "episode" }), response()); expect(mocks.acquirePlaybackSession).toHaveBeenCalledTimes(3); expect(mocks.acquirePlaybackSession).toHaveBeenNthCalledWith(1, { customerId: 7, consumerKeyHash }); expect(mocks.acquirePlaybackSession).toHaveBeenNthCalledWith(2, { customerId: 7, consumerKeyHash }); expect(mocks.acquirePlaybackSession).toHaveBeenNthCalledWith(3, { customerId: 7, consumerKeyHash }); });
  it("recusa outro consumidor no limite global antes de buscar qualquer origem", async () => { const route = handler(); mocks.readPlaybackTicket.mockResolvedValue(ticket("vod", 9)); mocks.acquirePlaybackSession.mockResolvedValue({ allowed: false, activeSessions: 2, expiresAt: null }); const denied = response(); await route(request({ ticket: "blocked" }), denied); expect(denied.status).toHaveBeenCalledWith(429); expect(mocks.getVodItemById).not.toHaveBeenCalled(); });
  it("resolve filme e episódio sem devolver credenciais ou URL ao cliente", async () => { const route = handler(); mocks.readPlaybackTicket.mockResolvedValueOnce(ticket("vod", 9)).mockResolvedValueOnce(ticket("episode", 10)); mocks.getVodItemById.mockResolvedValue({ sourceUrl: "https://vod.exemplo/filme.mkv" }); mocks.getVodEpisodeById.mockResolvedValue({ sourceUrl: "https://vod.exemplo/episodio.m3u8" }); const movie = response(); const episode = response(); await route(request({ ticket: "movie" }), movie); await route(request({ ticket: "episode" }), episode); expect(movie.json).toHaveBeenCalledWith(expect.objectContaining({ url: "https://vod.exemplo/filme.mkv" })); expect(episode.json).toHaveBeenCalledWith(expect.objectContaining({ url: "https://vod.exemplo/episodio.m3u8" })); });
});
