/** Contratos tRPC administrativos e contratos mínimos para o aplicativo final. */
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import type { AppPixCharge, AppSubscriptionSnapshot } from "@shared/types";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, publicProcedure, router } from "./_core/trpc";
import * as db from "./db";
import { createMercadoPagoPix, getVodMetadataByTmdbId, searchVodMetadata } from "./externalIntegrations";
import { inspectM3uManifest } from "./m3uInspection";
import { syncEpgSource } from "./epgSync";
import { isMediaSourceUrl } from "./mediaSource";
import { createAdminSession } from "./adminSession";
import { signAndroidManifest } from "./androidUpdates";

const customerStatus = z.enum(["active", "attention", "expired"]);
const vodKind = z.enum(["filme", "serie", "novela"]);
const cycleKind = z.enum(["monthly", "quarterly", "semiannual", "annual", "custom"]);
const deviceInput = z.object({ username: z.string().regex(/^\d{6,16}$/, "Usuário Xtream deve conter somente números."), password: z.string().regex(/^\d{6,32}$/, "Senha Xtream deve conter somente números.") });
const mediaSourceUrl = z.string().trim().min(1).refine(isMediaSourceUrl, "Informe uma URL HTTP ou HTTPS válida.");

function cyclePrice(monthlyPriceCents: number, intervalDays: number, discountPercent: number) {
  return Math.round(monthlyPriceCents * (intervalDays / 30) * (1 - discountPercent / 100));
}
async function requireAppCustomer(input: z.infer<typeof deviceInput>) { const customer = await db.getCustomerByXtreamCredentials(input.username, input.password); if (!customer) throw new TRPCError({ code: "UNAUTHORIZED", message: "Credenciais Xtream inválidas" }); return customer; }

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => { if (!opts.ctx.user) return null; const { passwordHash: _passwordHash, ...safeUser } = opts.ctx.user; return safeUser; }),
    login: publicProcedure.input(z.object({ username: z.string().trim().min(3).max(64), password: z.string().min(1).max(256) })).mutation(async ({ input, ctx }) => { const admin = await db.authenticateAdmin(input.username, input.password); if (!admin) throw new TRPCError({ code: "UNAUTHORIZED", message: "Usuário ou senha inválidos." }); const session = await createAdminSession(admin); ctx.res.cookie(COOKIE_NAME, session, getSessionCookieOptions(ctx.req)); return { success: true } as const; }),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  plans: router({
    list: adminProcedure.query(() => db.listPlans()),
    create: adminProcedure.input(z.object({ name: z.string().min(2).max(100), monthlyPriceCents: z.number().int().positive(), screenLimit: z.number().int().min(1).max(10), trialDays: z.number().int().min(0).max(90), cycles: z.array(z.object({ cycle: cycleKind, intervalDays: z.number().int().min(1).max(730), discountPercent: z.number().int().min(0).max(100) })).min(1) })).mutation(({ input }) => db.createPlan(input)),
  }),
  customers: router({
    list: adminProcedure.query(() => db.listCustomers()),
    create: adminProcedure.input(z.object({ label: z.string().min(2).max(90), email: z.string().email().nullable().optional(), phone: z.string().min(8).max(30).nullable().optional(), planId: z.number().int().positive(), planCycleId: z.number().int().positive() })).mutation(({ input }) => db.createCustomer(input)),
    setStatus: adminProcedure.input(z.object({ id: z.number().int().positive(), status: customerStatus })).mutation(({ input }) => db.updateCustomerStatus(input.id, input.status)),
    updateProfile: adminProcedure.input(z.object({ id: z.number().int().positive(), label: z.string().min(2).max(90), email: z.string().email().nullable().optional(), phone: z.string().min(8).max(30).nullable().optional() })).mutation(({ input }) => db.updateCustomerProfile(input)),
    rotateXtreamPassword: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => db.rotateXtreamPassword(input.id)),
    listDevices: adminProcedure.input(z.object({ customerId: z.number().int().positive() })).query(({ input }) => db.listCustomerDevices(input.customerId)),
    removeDevice: adminProcedure.input(z.object({ customerId: z.number().int().positive(), deviceId: z.number().int().positive() })).mutation(({ input }) => db.removeCustomerDevice(input)),
    listPlaybackSessions: adminProcedure.input(z.object({ customerId: z.number().int().positive() })).query(({ input }) => db.listActivePlaybackSessions(input.customerId)),
    terminatePlaybackSession: adminProcedure.input(z.object({ customerId: z.number().int().positive(), sessionId: z.number().int().positive() })).mutation(({ input }) => db.terminatePlaybackSession(input)),
  }),
  channels: router({ list: adminProcedure.query(() => db.listChannels()), inspectManifest: adminProcedure.input(z.object({ sourceUrl: z.string().url() })).mutation(({ input }) => inspectM3uManifest(input.sourceUrl)), create: adminProcedure.input(z.object({ name: z.string().min(2).max(140), groupTitle: z.string().min(2).max(90), channelNumber: z.number().int().positive(), epgId: z.string().max(160).nullable().optional(), logoUrl: z.string().url().nullable().optional(), ageRating: z.number().int().min(0).max(18), sources: z.array(z.object({ quality: z.enum(["SD", "HD", "FHD", "4K", "AUTO"]), primaryUrl: z.string().url(), primaryOrigin: z.string().url().nullable().optional(), primaryReferer: z.string().url().nullable().optional(), fallbackUrl: z.string().url().nullable().optional(), fallbackOrigin: z.string().url().nullable().optional(), fallbackReferer: z.string().url().nullable().optional() })).min(1).max(4) })).mutation(({ input }) => db.createChannel(input)), toggle: adminProcedure.input(z.object({ id: z.number().int().positive(), isActive: z.boolean() })).mutation(({ input }) => db.toggleChannel(input.id, input.isActive)) }),
  epg: router({ list: adminProcedure.query(() => db.listEpgSources()), create: adminProcedure.input(z.object({ name: z.string().min(2).max(140), feedUrl: z.string().url(), refreshThresholdHours: z.number().int().min(1).max(72).default(6) })).mutation(({ input }) => db.createEpgSource(input)), syncNow: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => syncEpgSource(input.id, { force: true })) }),
  vod: router({
    list: adminProcedure.query(() => db.listVodItems()),
    create: adminProcedure.input(z.object({ title: z.string().min(2).max(255), kind: vodKind, tmdbId: z.number().int().positive().max(99_999_999).nullable().optional(), releaseYear: z.number().int().min(1888).max(3000).nullable().optional(), sourceUrl: mediaSourceUrl.nullable().optional(), synopsis: z.string().max(5000).nullable().optional(), posterUrl: z.string().url().nullable().optional(), ageRating: z.number().int().min(0).max(18).default(0) })).mutation(({ input }) => db.createVodItem(input)),
    searchMetadata: adminProcedure.input(z.object({ query: z.string().min(2).max(120) })).mutation(({ input }) => searchVodMetadata(input.query)),
    lookupMetadata: adminProcedure.input(z.object({ tmdbId: z.number().int().positive().max(99_999_999), kind: vodKind })).mutation(({ input }) => getVodMetadataByTmdbId(input)),
    seasons: adminProcedure.input(z.object({ vodId: z.number().int().positive() })).query(({ input }) => db.listVodSeasons(input.vodId)),
    episodes: adminProcedure.input(z.object({ vodId: z.number().int().positive() })).query(({ input }) => db.listVodEpisodes(input.vodId)),
    createSeason: adminProcedure.input(z.object({ vodId: z.number().int().positive(), seasonNumber: z.number().int().positive(), title: z.string().max(255).nullable().optional() })).mutation(({ input }) => db.createVodSeason(input)),
    createEpisode: adminProcedure.input(z.object({ vodId: z.number().int().positive(), seasonId: z.number().int().positive().nullable().optional(), episodeNumber: z.number().int().positive(), title: z.string().min(1).max(255), sourceUrl: mediaSourceUrl })).mutation(({ input }) => db.createVodEpisode(input)),
  }),
  integrations: router({ list: adminProcedure.query(() => db.listIntegrationSettings()), save: adminProcedure.input(z.object({ provider: z.enum(["mercado_pago", "vod_metadata"]), label: z.string().min(2).max(120), baseUrl: z.string().url().nullable().optional(), enabled: z.boolean(), secret: z.string().min(6).max(2048).nullable().optional() })).mutation(({ input }) => db.saveIntegrationSetting(input)) }),
  androidUpdates: router({ list: adminProcedure.query(() => db.listAndroidReleases()), create: adminProcedure.input(z.object({ versionCode: z.number().int().positive().max(2_000_000_000), versionName: z.string().trim().min(1).max(80), apkUrl: z.string().url().refine(url => new URL(url).protocol === "https:", "A URL do APK deve usar HTTPS."), apkSizeBytes: z.number().int().positive().max(2_000_000_000), sha256: z.string().regex(/^[a-fA-F0-9]{64}$/, "Informe um SHA-256 hexadecimal de 64 caracteres."), minimumSupportedVersionCode: z.number().int().positive().max(2_000_000_000).nullable().optional(), mandatory: z.boolean().default(false), releaseNotes: z.string().trim().min(1).max(5000) })).mutation(({ input }) => db.createAndroidRelease(input)), publish: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const release = await db.getAndroidReleaseById(input.id); if (!release) throw new TRPCError({ code: "NOT_FOUND", message: "Release Android não encontrada." }); const signed = signAndroidManifest(release); await db.publishAndroidRelease({ id: release.id, ...signed }); return { success: true } as const; }), archive: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => db.archiveAndroidRelease(input.id)) }),
  billing: router({ createPix: adminProcedure.input(z.object({ customerId: z.number().int().positive(), payerEmail: z.string().email(), amountCents: z.number().int().positive(), description: z.string().min(2).max(255) })).mutation(async ({ input }) => { const customer = await db.getCustomerById(input.customerId); if (!customer) throw new Error("Cliente não encontrado"); const externalReference = `videlis-${customer.id}-${Date.now()}`; const payment = await createMercadoPagoPix({ ...input, externalReference }); await db.createPixCharge({ customerId: customer.id, amountCents: input.amountCents, providerPaymentId: payment.providerPaymentId, externalReference, qrCode: payment.qrCode, qrCodeBase64: payment.qrCodeBase64, dueAt: new Date(Date.now() + 30 * 60 * 1000) }); return payment; }), listForCustomer: adminProcedure.input(z.object({ customerId: z.number().int().positive() })).query(({ input }) => db.listPixChargesForCustomer(input.customerId)) }),
  app: router({
    profile: publicProcedure.input(deviceInput).query(async ({ input }) => { const customer = await requireAppCustomer(input); const activeSessions = await db.listActivePlaybackSessions(customer.id); return { label: customer.label, email: customer.email, phone: customer.phone, plan: customer.plan, screenLimit: customer.screenLimit, usedScreens: customer.usedScreens, activeScreens: activeSessions.length }; }),
    updateProfile: publicProcedure.input(deviceInput.extend({ label: z.string().trim().min(2).max(90), email: z.string().email().nullable().optional(), phone: z.string().min(8).max(30).nullable().optional() })).mutation(async ({ input }) => { const customer = await requireAppCustomer(input); await db.updateCustomerProfile({ id: customer.id, label: input.label, email: input.email, phone: input.phone }); return { success: true } as const; }),
    devices: publicProcedure.input(deviceInput).query(async ({ input }) => { const customer = await requireAppCustomer(input); return db.listCustomerDevices(customer.id); }),
    registerDevice: publicProcedure.input(deviceInput.extend({ deviceName: z.string().trim().min(1).max(120), deviceKey: z.string().min(16).max(200) })).mutation(async ({ input }) => { const customer = await requireAppCustomer(input); try { return await db.registerCustomerDevice({ customerId: customer.id, deviceName: input.deviceName, deviceKey: input.deviceKey }); } catch (error) { throw new TRPCError({ code: "FORBIDDEN", message: error instanceof Error ? error.message : "Não foi possível registrar o dispositivo" }); } }),
    removeDevice: publicProcedure.input(deviceInput.extend({ deviceId: z.number().int().positive() })).mutation(async ({ input }) => { const customer = await requireAppCustomer(input); try { await db.removeCustomerDevice({ customerId: customer.id, deviceId: input.deviceId }); return { success: true } as const; } catch (error) { throw new TRPCError({ code: "NOT_FOUND", message: error instanceof Error ? error.message : "Dispositivo não encontrado" }); } }),
    subscription: publicProcedure.input(deviceInput).query(async ({ input }) => { const customer = await db.getCustomerByXtreamCredentials(input.username, input.password); if (!customer) throw new TRPCError({ code: "UNAUTHORIZED", message: "Credenciais Xtream inválidas" }); const days = Math.ceil((customer.expiresAt.getTime() - Date.now()) / 86_400_000); const state = customer.status === "expired" || days < 0 ? "expired" : customer.status === "attention" || days <= 3 ? "attention" : "active"; const subscription: AppSubscriptionSnapshot = { state, expiresAt: customer.expiresAt.getTime(), showExpiryPopup: state !== "active", accessAllowed: state !== "expired", message: state === "active" ? "Assinatura ativa." : state === "attention" ? "Sua assinatura está próxima do vencimento." : "Sua assinatura venceu. Gere um novo PIX para continuar." }; const latest = (await db.listPixChargesForCustomer(customer.id))[0]; const charge: AppPixCharge | null = latest ? { paymentId: latest.providerPaymentId || `charge-${latest.id}`, status: latest.status, qrCode: latest.qrCode, qrCodeBase64: latest.qrCodeBase64, expiresAt: latest.dueAt.getTime() } : null; return { subscription, charge }; }),
    planOptions: publicProcedure.input(deviceInput).query(async ({ input }) => { const customer = await db.getCustomerByXtreamCredentials(input.username, input.password); if (!customer) throw new TRPCError({ code: "UNAUTHORIZED", message: "Credenciais Xtream inválidas" }); const availablePlans = await db.listPlans(); return availablePlans.filter(plan => plan.isActive).map(plan => ({ id: plan.id, name: plan.name, screenLimit: plan.screenLimit, trialDays: plan.trialDays, current: plan.id === customer.planId, cycles: plan.cycles.filter(cycle => cycle.isActive).map(cycle => ({ id: cycle.id, cycle: cycle.cycle, intervalDays: cycle.intervalDays, discountPercent: cycle.discountPercent, priceCents: cyclePrice(plan.monthlyPriceCents, cycle.intervalDays, cycle.discountPercent) })) })); }),
    previewPlanChange: publicProcedure.input(deviceInput.extend({ planId: z.number().int().positive(), planCycleId: z.number().int().positive() })).query(async ({ input }) => { const customer = await db.getCustomerByXtreamCredentials(input.username, input.password); const cycle = await db.getPlanCycle(input.planCycleId); const availablePlans = await db.listPlans(); const plan = availablePlans.find(item => item.id === input.planId); if (!customer || !plan || !cycle || cycle.planId !== plan.id) throw new TRPCError({ code: "BAD_REQUEST", message: "Opção de plano inválida" }); const priceCents = cyclePrice(plan.monthlyPriceCents, cycle.intervalDays, cycle.discountPercent); return { direction: plan.screenLimit > customer.screenLimit ? "upgrade" : plan.screenLimit < customer.screenLimit ? "downgrade" : "change", planName: plan.name, screenLimit: plan.screenLimit, intervalDays: cycle.intervalDays, discountPercent: cycle.discountPercent, priceCents }; }),
    changePlan: publicProcedure.input(deviceInput.extend({ planId: z.number().int().positive(), planCycleId: z.number().int().positive(), payerEmail: z.string().email() })).mutation(async ({ input }) => { const customer = await requireAppCustomer(input); const cycle = await db.getPlanCycle(input.planCycleId); const plan = (await db.listPlans()).find(item => item.id === input.planId); if (!plan || !cycle || cycle.planId !== plan.id || !plan.isActive || !cycle.isActive) throw new TRPCError({ code: "BAD_REQUEST", message: "Opção de plano inválida" }); const amountCents = cyclePrice(plan.monthlyPriceCents, cycle.intervalDays, cycle.discountPercent); const externalReference = `videlis-plan-${customer.id}-${Date.now()}`; const payment = await createMercadoPagoPix({ amountCents, payerEmail: input.payerEmail, externalReference, description: `Alteração de plano Videlis · ${plan.name}` }); await db.createPixCharge({ customerId: customer.id, amountCents, providerPaymentId: payment.providerPaymentId, externalReference, requestedPlanId: plan.id, requestedPlanCycleId: cycle.id, qrCode: payment.qrCode, qrCodeBase64: payment.qrCodeBase64, dueAt: new Date(Date.now() + 30 * 60 * 1000) }); return { status: "pending" as const, planName: plan.name, screenLimit: plan.screenLimit, amountCents, paymentId: payment.providerPaymentId, qrCode: payment.qrCode, qrCodeBase64: payment.qrCodeBase64 }; }),
    catalog: publicProcedure.input(deviceInput).query(async ({ input }) => { await requireAppCustomer(input); const [channels, allVod] = await Promise.all([db.listChannels(), db.listVodItems()]); const vod = allVod.filter(item => item.status === "ready"); const signal = (ageRating: number) => ({ ageRating, requiresAdultPin: ageRating >= 18 }); const liveChannels = channels.filter(channel => channel.isActive && channel.healthStatus !== "unavailable"); const episodicVod = vod.filter(item => item.kind !== "filme"); const episodeGroups = await Promise.all(episodicVod.map(async item => [item.id, await db.listVodEpisodes(item.id)] as const)); const programmes = await db.listEpgProgrammes(liveChannels.flatMap(channel => channel.epgId ? [channel.epgId] : [])); const channelIdByEpgId = new Map(liveChannels.flatMap(channel => channel.epgId ? [[channel.epgId, channel.id] as const] : [])); return { adultControl: { mode: "client_local", threshold: 18, note: "A API não recebe nem armazena PIN; o aplicativo decide o bloqueio local." }, playback: { credentialTransport: "headers", usernameHeader: "x-videlis-username", passwordHeader: "x-videlis-password", deviceIdHeader: "x-videlis-device-id" }, channels: liveChannels.map(channel => ({ id: channel.id, name: channel.name, groupTitle: channel.groupTitle, channelNumber: channel.channelNumber, logoUrl: channel.logoUrl, epgId: channel.epgId, qualities: channel.qualities, playbackPath: `/api/app/playback/live/${channel.id}`, ...signal(channel.ageRating) })), vod: vod.map(item => ({ id: item.id, title: item.title, kind: item.kind, tmdbId: item.tmdbId, synopsis: item.synopsis, posterUrl: item.posterUrl, releaseYear: item.releaseYear, playbackPath: item.kind === "filme" ? `/api/app/playback/movie/${item.id}` : null, ...signal(item.ageRating) })), episodes: episodeGroups.flatMap(([vodId, episodes]) => { const parent = vod.find(item => item.id === vodId); return episodes.map(episode => ({ id: episode.id, vodId, seasonId: episode.seasonId, episodeNumber: episode.episodeNumber, title: episode.title, publishedAt: episode.publishedAt, playbackPath: `/api/app/playback/episode/${episode.id}`, ...(signal(parent?.ageRating ?? 0)) })); }), epg: programmes.map(programme => ({ id: programme.id, channelId: channelIdByEpgId.get(programme.channelEpgId) ?? null, channelEpgId: programme.channelEpgId, title: programme.title, synopsis: programme.synopsis, startsAt: programme.startsAt, endsAt: programme.endsAt, ...signal(programme.ageRating) })) }; }),
  }),
});

export type AppRouter = typeof appRouter;
