import { useState } from "react";
import { MonitorSmartphone, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { PanelConfirmDialog } from "@/components/PanelActionDialog";
import { trpc } from "@/lib/trpc";

type CustomerDevicesDialogProps = { open: boolean; onOpenChange: (open: boolean) => void; customer: { id: number; label: string; screenLimit: number; usedScreens: number } };

export function CustomerDevicesDialog({ open, onOpenChange, customer }: CustomerDevicesDialogProps) {
  const utils = trpc.useUtils(); const [target, setTarget] = useState<{ id: number; name: string } | null>(null);
  const devices = trpc.customers.listDevices.useQuery({ customerId: customer.id }, { enabled: open });
  const remove = trpc.customers.removeDevice.useMutation({ onSuccess: async () => { setTarget(null); await Promise.all([utils.customers.listDevices.invalidate({ customerId: customer.id }), utils.customers.list.invalidate()]); toast.success("Dispositivo removido e vaga liberada."); }, onError: error => toast.error(error.message) });
  return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-lg border-white/[.11] bg-[#10191f] text-slate-100"><DialogHeader><DialogTitle className="text-xl font-extrabold tracking-tight">Telas ativas</DialogTitle><DialogDescription className="text-slate-400">{customer.label} utiliza {customer.usedScreens} de {customer.screenLimit} telas. A remoção libera a vaga para o aplicativo.</DialogDescription></DialogHeader><div className="mt-2 space-y-2">{devices.isLoading ? <p className="rounded-xl border border-white/[.07] px-4 py-6 text-center text-sm text-slate-500">Carregando dispositivos…</p> : null}{devices.error ? <p className="rounded-xl border border-[#ff6b5b]/20 bg-[#ff6b5b]/[.06] px-4 py-4 text-sm text-[#ffaaa2]">Não foi possível carregar os dispositivos.</p> : null}{!devices.isLoading && !devices.error && !devices.data?.length ? <p className="rounded-xl border border-dashed border-white/[.1] px-4 py-7 text-center text-sm text-slate-500">Nenhuma tela ativa foi registrada.</p> : null}{devices.data?.map(device => <div key={device.id} className="flex items-center gap-3 rounded-xl border border-white/[.08] bg-black/10 p-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#43E6C2]/[.09]"><MonitorSmartphone className="h-4 w-4 text-[#9df6df]" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-100">{device.deviceName}</p><p className="mt-0.5 font-mono text-[9px] uppercase tracking-[.12em] text-slate-500">Tela {device.slot} · vista em {new Date(device.lastSeenAt).toLocaleString("pt-BR")}</p></div><button type="button" onClick={() => setTarget({ id: device.id, name: device.deviceName })} className="pressable rounded-lg p-2 text-slate-500 transition hover:bg-[#ff6b5b]/10 hover:text-[#ffaaa2]" title="Remover dispositivo"><Trash2 className="h-4 w-4" /></button></div>)}</div></DialogContent></Dialog><PanelConfirmDialog open={Boolean(target)} onOpenChange={next => { if (!next) setTarget(null); }} title="Remover tela ativa" description={target ? `Remover ${target.name}? O aplicativo poderá ocupar a vaga novamente em outro dispositivo.` : ""} confirmLabel="Remover dispositivo" submitting={remove.isPending} onConfirm={() => target && remove.mutate({ customerId: customer.id, deviceId: target.id })} /></>;
}
