/**
 * Diálogos próprios do Nexus Stream para entradas, confirmações e avisos.
 * Eles substituem completamente prompt/confirm/alert nativos do navegador.
 */
import { useState } from "react";
import { CheckCircle2, CircleAlert, Copy, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export type PanelField = { name: string; label: string; placeholder?: string; type?: "text" | "email" | "number"; defaultValue?: string; options?: Array<{ value: string; label: string }>; optional?: boolean; wide?: boolean };

export function PanelFormDialog({ open, onOpenChange, title, description, fields, submitLabel, submitting, onSubmit }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; fields: PanelField[]; submitLabel: string; submitting?: boolean; onSubmit: (values: Record<string, string>) => void }) {
  const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(fields.map(field => [field.name, field.defaultValue ?? ""])));
  const submit = () => { if (fields.some(field => !field.optional && !values[field.name]?.trim())) return; onSubmit(values); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent showCloseButton={false} className="flex max-h-[calc(100dvh-1.5rem)] flex-col border-white/[0.1] bg-[#10191f] p-0 text-slate-100 shadow-[0_20px_80px_rgba(0,0,0,.5)] sm:max-w-2xl"><div className="shrink-0 border-b border-white/[0.07] px-5 py-4"><DialogHeader><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#9df6df]">Ação administrativa</p><DialogTitle className="text-lg font-extrabold tracking-[-0.04em] text-white">{title}</DialogTitle><DialogDescription className="pt-1 text-sm leading-5 text-slate-400">{description}</DialogDescription></DialogHeader></div><form onSubmit={event => { event.preventDefault(); submit(); }} className="grid min-h-0 grid-cols-1 gap-x-4 gap-y-3 overflow-y-auto p-5 sm:grid-cols-2">{fields.map(field => <label key={field.name} className={`form-label ${field.wide ? "sm:col-span-2" : ""}`}>{field.label}{field.options ? <select value={values[field.name] ?? ""} onChange={event => setValues(current => ({ ...current, [field.name]: event.target.value }))} className="form-input mt-1.5 normal-case">{field.options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input type={field.type ?? "text"} value={values[field.name] ?? ""} onChange={event => setValues(current => ({ ...current, [field.name]: event.target.value }))} placeholder={field.placeholder} className="form-input mt-1.5 normal-case" autoFocus={field === fields[0]} />}</label>)}<div className="sticky bottom-0 z-10 -mx-5 -mb-5 mt-2 flex flex-col-reverse gap-2 border-t border-white/[0.07] bg-[#10191f] px-5 py-4 sm:col-span-2 sm:flex-row sm:justify-end"><button type="button" onClick={() => onOpenChange(false)} className="pressable rounded-xl border border-white/[0.1] px-4 py-2.5 text-sm font-bold text-slate-300">Cancelar</button><button type="submit" disabled={submitting} className="pressable rounded-xl bg-[#43E6C2] px-4 py-2.5 text-sm font-bold text-[#07201c] disabled:cursor-wait disabled:opacity-60">{submitting ? "Salvando" : submitLabel}</button></div></form></DialogContent></Dialog>;
}

export function PanelConfirmDialog({ open, onOpenChange, title, description, confirmLabel, tone = "default", submitting, onConfirm }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; confirmLabel: string; tone?: "default" | "danger"; submitting?: boolean; onConfirm: () => void }) {
  const actionClass = tone === "danger" ? "bg-[#ff6b5b] text-white hover:bg-[#ff8478]" : "bg-[#43E6C2] text-[#07201c] hover:bg-[#72f0d5]";
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent showCloseButton={false} className="border-white/[0.1] bg-[#10191f] p-0 text-slate-100 shadow-[0_20px_80px_rgba(0,0,0,.5)] sm:max-w-md"><div className="p-6"><CircleAlert className={`h-7 w-7 ${tone === "danger" ? "text-[#ff6b5b]" : "text-[#ffbb4d]"}`} /><DialogHeader className="mt-5"><DialogTitle className="text-xl font-extrabold tracking-[-0.04em] text-white">{title}</DialogTitle><DialogDescription className="leading-6 text-slate-400">{description}</DialogDescription></DialogHeader><div className="mt-7 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={() => onOpenChange(false)} className="pressable rounded-xl border border-white/[0.1] px-4 py-3 text-sm font-bold text-slate-300">Voltar</button><button type="button" disabled={submitting} onClick={onConfirm} className={`pressable rounded-xl px-4 py-3 text-sm font-bold disabled:cursor-wait disabled:opacity-60 ${actionClass}`}>{submitting ? "Processando" : confirmLabel}</button></div></div></DialogContent></Dialog>;
}

export function PanelAlertDialog({ open, onOpenChange, title, description, secret, onCopy }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; secret?: string | null; onCopy?: () => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent showCloseButton={false} className="border-white/[0.1] bg-[#10191f] p-0 text-slate-100 shadow-[0_20px_80px_rgba(0,0,0,.5)] sm:max-w-lg"><div className="p-6"><CheckCircle2 className="h-7 w-7 text-[#43E6C2]" /><DialogHeader className="mt-5"><DialogTitle className="text-xl font-extrabold tracking-[-0.04em] text-white">{title}</DialogTitle><DialogDescription className="leading-6 text-slate-400">{description}</DialogDescription></DialogHeader>{secret ? <div className="mt-5 flex gap-2 rounded-xl border border-[#43E6C2]/15 bg-[#43E6C2]/[0.04] p-3"><code className="min-w-0 flex-1 break-all text-xs text-slate-100">{secret}</code><button type="button" onClick={onCopy} className="pressable inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-[#43E6C2]/20 text-[#9df6df]"><Copy className="h-3.5 w-3.5" /><span className="sr-only">Copiar</span></button></div> : null}<button type="button" onClick={() => onOpenChange(false)} className="pressable mt-7 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#43E6C2] px-4 py-3 text-sm font-bold text-[#07201c]"><X className="h-4 w-4" /> Concluir</button></div></DialogContent></Dialog>;
}
