import { useState } from "react";
import { CheckCircle2, CircleAlert, Copy, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export type PanelField = { name: string; label: string; placeholder?: string; type?: "text" | "email" | "number"; defaultValue?: string; options?: Array<{ value: string; label: string }>; optional?: boolean; wide?: boolean };
export function PanelFormDialog({ open, onOpenChange, title, description, fields, submitLabel, submitting, onSubmit }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; fields: PanelField[]; submitLabel: string; submitting?: boolean; onSubmit: (values: Record<string, string>) => void }) {
 const [values, setValues] = useState<Record<string,string>>(() => Object.fromEntries(fields.map(f=>[f.name,f.defaultValue??""]))); const [expanded,setExpanded]=useState<Record<string,boolean>>({}); const visible=fields.filter(f=>!f.optional||expanded[f.name]);
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent showCloseButton={false} className="flex max-h-[calc(100dvh-1.5rem)] flex-col border-white/[.1] bg-[#10191f] p-0 text-slate-100 sm:max-w-2xl"><div className="shrink-0 border-b border-white/[.07] px-5 py-4"><DialogHeader><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#9df6df]">Ação administrativa</p><DialogTitle className="text-lg font-extrabold text-white">{title}</DialogTitle><DialogDescription className="text-sm text-slate-400">{description}</DialogDescription></DialogHeader></div><form onSubmit={e=>{e.preventDefault();if(!fields.some(f=>!f.optional&&!values[f.name]?.trim()))onSubmit(values)}} className="grid overflow-y-auto p-5 sm:grid-cols-2 gap-3">{visible.map(f=><label key={f.name} className={`form-label ${f.wide?"sm:col-span-2":""}`}>{f.label}{f.options?<Select value={values[f.name] || undefined} onValueChange={value=>setValues(v=>({...v,[f.name]:value}))}><SelectTrigger className="mt-1.5 h-[45px] w-full border-white/[.1] bg-white/[.035] text-slate-100 hover:bg-white/[.055]"><SelectValue placeholder={`Selecione ${f.label.toLowerCase()}`} /></SelectTrigger><SelectContent className="border-white/[.1] bg-[#10191f] text-slate-100">{f.options.map(o=><SelectItem key={o.value} value={o.value} className="cursor-pointer text-slate-100 focus:bg-[#43E6C2]/15 focus:text-white data-[state=checked]:bg-white/[.06]">{o.label}</SelectItem>)}</SelectContent></Select>:<input type={f.type??"text"} value={values[f.name]??""} onChange={e=>setValues(v=>({...v,[f.name]:e.target.value}))} placeholder={f.placeholder} className="form-input mt-1.5" />}</label>)}{fields.filter(f=>f.optional&&!expanded[f.name]).map(f=><button key={f.name} type="button" onClick={()=>setExpanded(s=>({...s,[f.name]:true}))} className="pressable text-left text-xs font-bold text-[#9df6df]">+ Adicionar {f.label}</button>)}<div className="sm:col-span-2 flex justify-end gap-2 border-t border-white/[.07] pt-4"><button type="button" onClick={()=>onOpenChange(false)} className="pressable rounded-xl border border-white/[.1] px-4 py-2.5 text-sm font-bold">Cancelar</button><button type="submit" disabled={submitting} className="pressable rounded-xl bg-[#43E6C2] px-4 py-2.5 text-sm font-bold text-[#07201c]">{submitting?"Salvando":submitLabel}</button></div></form></DialogContent></Dialog>;
}
export function PanelConfirmDialog({ open,onOpenChange,title,description,confirmLabel,tone="default",submitting,onConfirm }: {open:boolean;onOpenChange:(v:boolean)=>void;title:string;description:string;confirmLabel:string;tone?:"default"|"danger";submitting?:boolean;onConfirm:()=>void}) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="bg-[#10191f] text-slate-100"><CircleAlert className="text-[#ffbb4d]"/><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription><button onClick={onConfirm} disabled={submitting}>{confirmLabel}</button></DialogContent></Dialog> }
export function PanelAlertDialog({open,onOpenChange,title,description,secret,onCopy}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;description:string;secret?:string|null;onCopy?:()=>void}) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="bg-[#10191f] text-slate-100"><CheckCircle2/><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription>{secret?<button onClick={onCopy}><Copy/> {secret}</button>:null}<button onClick={()=>onOpenChange(false)}><X/> Concluir</button></DialogContent></Dialog> }
